title: ""
description: "A constellation of projects, analytics, and process design."
remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "default"

# Site settings
locale: "en-US"
url: "https://bmcauley.github.io"
baseurl: ""   # IMPORTANT: must be empty for username.github.io sites
show_excerpts: false
paginate: false

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-include-cache

# Author settings
author:
  sidebar: true
  name: "Bennett McAuley"
  avatar: "assets/images/my-notion-face-transparent.png"
  bio: "Born to be an overthinker, trained to be a statistician, proven to be an advocate for all."
  location: "RTP, NC"
  uri: null
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/bennett-mcauley/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Pages
collections:
  pages:
    output: true
    permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      published: false

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
   
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
    values:
      show_post_nav: false


# Removing feed
atom_feed:
  hide: true