# Site settings
title: ""
url: "https://bmcauley.github.io"
baseurl: ""
description: "A constellation of projects, analytics, and process design."
locale: "en-US"
show_excerpts: false
paginate: false

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "default"
include:
  - _pages
plugins:
  - jekyll-include-cache

# Author settings
author:
  sidebar: true
  name: "Bennett McAuley"
  avatar: "assets/images/my-notion-face-transparent.png"
  bio: "Born to be an overthinker, trained to be a statistician, proven to be an advocate for all."
  location: "RTP, NC"
  uri: null
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/bennett-mcauley/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bmcauley"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      published: false

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      show_post_nav: false

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true

portfolio:
  output: true
  permalink: /:collection/:path/

# Removing feed
atom_feed:
  hide: true